### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by cuge1995** [Na-Z/PS-2Net#1]
when run "python main_P2/train.py --dataset_name ScanNet --dataset_size 93402 --data_dir ./datasets/ScanNet/P2/ --classes 21 --input_feat 3 --log_dir log"

PS-2Net/models/model.py", line 58, in __init__
    self.input_data = torch.FloatTensor(self.opt.batch_size, 9, self.opt.num_point).uniform_()
AttributeError: 'Namespace' object has no attribute 'num_point'

**Comment by Na-Z** [comment]
Thanks for pointing out the bug. I have fixed it and updated the repo. Please refer to the latest commit.

**Comment by cuge1995** [comment]
thanks for this awesome work

**Comment by cuge1995** [comment]
still cannot run successfully

Training begins..
mode-train:(13933, 8192, 3),(13933, 8192)
Traceback (most recent call last):
  File "main_P2/train.py", line 154, in <module>
    model.optimize()
  File "/home/amax/Pointnet2.ScanNet/PS-2Net/models/model.py", line 90, in optimize
    self.forward(epoch=epoch)
  File "/home/amax/Pointnet2.ScanNet/PS-2Net/models/model.py", line 82, in forward
    self.score = self.network(self.data, self.knn_idx)
  File "/home/amax/anaconda3/envs/scannet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/amax/Pointnet2.ScanNet/PS-2Net/models/network.py", line 335, in forward
    x = self.stacked_encoders[i](x, knn_idx)
  File "/home/amax/anaconda3/envs/scannet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/amax/Pointnet2.ScanNet/PS-2Net/models/network.py", line 155, in forward
    local_feat = self.featEX(edge_feat)
  File "/home/amax/anaconda3/envs/scannet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/amax/Pointnet2.ScanNet/PS-2Net/models/network.py", line 114, in forward
    x0 = self.mlp_layers[l](x)
  File "/home/amax/anaconda3/envs/scannet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/amax/Pointnet2.ScanNet/PS-2Net/models/layers.py", line 171, in forward
    x = self.conv(x)
  File "/home/amax/anaconda3/envs/scannet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/amax/anaconda3/envs/scannet/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDNN_STATUS_MAPPING_ERROR

**Comment by Na-Z** [comment]
Could you provide your system information? e.g., the version of pytorch, CUDA, cudnn..

**Comment by cuge1995** [comment]
torch 0.4.0
CUDA Version 10.2.89
cudnn:  " #define CUDNN_MAJOR 7
#define CUDNN_MINOR 6
#define CUDNN_PATCHLEVEL 5
--
#define CUDNN_VERSION (CUDNN_MAJOR * 1000 + CUDNN_MINOR * 100 + CUDNN_PATCHLEVEL) "

**Comment by Na-Z** [comment]
This repo is tested with torch 0.4.0 and CUDA 9.0.  I suspect the problem happened because of the CUDA version. 

Please first check with the following two points:
1. Make sure torch.cuda.is_available return True
2. Make sure your Nvidia driver is up-to-date. 

If it still doesn't work, maybe you should consider downgrade to CUDA9.0.
